apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-tssc-17-az-qua
  janus-idp.io/tekton: test-tssc-17-az-qua
  backstage.io/kubernetes-id: test-tssc-17-az-qua
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-tssc-17-az-qua
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
